# Meta
title: MONO GARDEN
description: |
  소광의 파란 파도가 망망히 닿아있는 애월의
  곽지 바닷가 한편에 일상 속 지친 나를 한 걸음 쉬게 해주는
  모노가든이 있습니다.

address: 제주특별자치도 제주시 애월읍 금성5길 44-16
tel: 010-8696-4164
location: http://naver.me/GIu8i8kw

url: 
baseurl: ''
repository: mozo-works/monogarden

timezone: 'Asia/Seoul'
permalink: pretty

amenities: '칫솔, 치약, 빗은 구비되어 있지 않습니다.'

# SEO
facebook:
  app_id: 
  publisher: 
logo: 

google_site_verification: 
google_analytics: 

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - README.md
  - LICENSE

sass:
  style: :compressed

kramdown:
  input: GFM
  syntax_highlighter: rouge
  entity_output: :as_input
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# collections
collections:
  rooms:
    output: true
    permalink: /room/:path/

defaults:
  -
    scope:
      path: _rooms
    values:
      layout: room
